### ISSUE TITLE
Issues module constructor

### ISSUE THREAD

**Issue by react-universe** [botisan-ai/gpt3-tokenizer#10]
I am getting this error after implementation
TypeError: gpt3_tokenizer__WEBPACK_IMPORTED_MODULE_3__.GPT3Tokenizer is not a constructor

**Comment by raphaelrk** [comment]
Try

```typescript
import GPT3Tokenizer from 'gpt3-tokenizer';
```

instead of

```typescript
import { GPT3Tokenizer } from 'gpt3-tokenizer';
```

**Comment by lhr0909** [comment]
Just checked the entry point of the code and it is in fact a default import. Will update the README soon!
