### ISSUE TITLE
Cannot create an instance of an abstract class (Typescript)

### ISSUE THREAD

**Issue by dluc** [botisan-ai/gpt3-tokenizer#11]
![image](https://user-images.githubusercontent.com/371009/206665560-771d2f98-bf8d-46fd-ad6c-f179ed7634ba.png)

![image](https://user-images.githubusercontent.com/371009/206665506-808032d7-8c59-4fa0-9504-df3ec7148738.png)

The docs should say `GPT3NodeTokenizer` right?

**Comment by lhr0909** [comment]
@dluc So if you notice `index.ts` in source, `GPT3NodeTokenizer` is a default export, so you can just name it to whatever you like during import.

```typescript
import GPT3Tokenizer from 'gpt3-tokenizer';
```

Hope this helps!
