### ISSUE TITLE
GPT3Tokenizer is not a constructor

### ISSUE THREAD

**Issue by rlin415** [botisan-ai/gpt3-tokenizer#12]
Hi, I get an error when trying to instantiate `GPT3Tokenizer`.
```
const tokenizer = new GPT3Tokenizer({ type: 'gpt3' });
                  ^

TypeError: GPT3Tokenizer is not a constructor
```
gpt3-tokenizer v1.1.4
Node.js v18.12.1

**Comment by lhr0909** [comment]
Make sure when you import, you are using the right import methods.

For TypeScript:

```
import GPT3Tokenizer from 'gpt3-tokenizer';
```

For NodeJS using `require`, you need to access the `default` field:

```
const GPT3Tokenizer = require('gpt3-tokenizer').default;
```

If you take a look at the [projects that uses this lib](https://github.com/botisan-ai/gpt3-tokenizer/network/dependents), you can find how other people are importing it. Hope this helps!

**Comment by andrewschmidt-a** [comment]
In ES Module you have to do GPT3Tokenizer.default even if using an import statement

so the call to fix the OP's issue would be:
const tokenizer = new GPT3Tokenizer.default({ type: 'gpt3' });
