### ISSUE TITLE
Unsafe use of `this.cache.hasOwnProperty`

### ISSUE THREAD

**Issue by kopertop** [botisan-ai/gpt3-tokenizer#13]
I started receiving errors about `this.cache.hasOwnProperty is not a function`. Digging into the code it looks like tokenizer.ts uses a bit of unsafe code considering `this.cache` is a map that allows any passed in value to be used as a token:

```
    if (this.cache.hasOwnProperty(token)) {
      return this.cache[token];
    }
```

Instead, this should be:

```
    if (Object.prototype.hasOwnProperty.call(this.cache, token)) {
      return this.cache[token];
    }
```

**Comment by Pullerz** [comment]
I'm also having this issue, would appreciate it if the PR was merged soon 🙏

**Comment by lhr0909** [comment]
@kopertop thank you so much for setting up the PR! Merged

@Pullerz please feel free to try it out with v1.1.5 and see if you have any more issues on your end.

**Comment by Pullerz** [comment]
@lhr0909 Working nicely for me now, thanks for fixing this!
